#!/bin/sh

# redirect errors to stdout -- just in case
exec 2>&1

# RUN IT ALL THROUGH lolcat FOR COLORING
# NOTE: needs -f to force color output since intermediate file is not a TTY
LOLCAT=/usr/games/lolcat
exec /usr/games/fortune | /usr/games/cowsay -n | $LOLCAT -f
